baseurl = "/"
languageCode = "en-us"
title = "Xu Cheng | 许程"
theme = "minimo"
googleAnalytics = "UA-136351319-1"
disqusShortname = "blog_xc"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents="↩"
hasCJKLanguage=true
enableEmoji=true
rssLimit=100

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    #name = "Home"#
	name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "订阅"
    url = "/index.xml"
	weight= 6

[params]
    description = "Personal website of Cheng Xu; 许程的个人网站"
    #footer = "&copy; [Xu Cheng]	#(https://xc9610.github.io/)# 	2019 | [Github](https://github.com/xc9610) | [Twitter](https://twitter.com/xieyihui)"#
	footer = "&copy; Xu Cheng	2019 | [Github](https://github.com/xc9610) "
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"

  disqusURL="https://xc9610.github.io/"

  customJS= ["js/fix-toc.js",
  "js/center-img.js",
  "js/right-quote.js",
  "js/no-highlight.js",
  "js/fix-footnote.js",
  "js/math-code.js",
  "js/external-link.js",
  "js/alt-title.js",
  "js/header-link.js"
  ]
  #githubContentURL: "https://github.com/rbind/yihui/edit/master/content/"
  #twitterImage: "/images/logo.png"

  # options for highlight.js (version, additional languages, and theme)
  #highlightjsVersion: "9.12.0"
 # highlightjsCDN: "//cdn.bootcss.com"
 # highlightjsLang: ["r", "yaml", "tex"]
  #highlightjsTheme: "github"

  #logo:
  #  en:
   #   img: "/images/logo.png"
    #  url: "/"
     # alt: "Yihui Xie"
     # tag: ""


 [author]
   en="Cheng Xu"
   cn="许程"
    #animation: "Yihui Xie & Lijia Yu"

[[lang]]
 [edit]
    cn="编辑"
 [license]
    cn= "版权"
 [subscribe]
    cn="订阅"

#blackfriday:
 #   extensionsmask: ["noIntraEmphasis"]
 #   fractions: false#